[package]
name = "doctown"
version = "7.0.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.100"
reqwest = "0.12.24"
tokio = { version = "1.48.0", features = ["full"] }
url = "2.5.7"
zip = "6.0.0"
